name: Generate Snake Animation

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake game from GitHub contributions
        uses: Platane/snk@v3
        with:
          github_user_name: hafsamaryam08  # Corrected username input
          output: dist/github-contribution-grid-snake.svg  # Corrected output path
          output_format: svg  # Ensures SVG format is used

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this secret is set
